POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "mytest@user.com",
  "password": "111"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "mytest@user.com",
  "password": "111"
}